export const GAME_STATES = {
    LOADING: 'LOADING',
    MAIN_MENU: 'MAIN_MENU',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
    OPTIONS: 'OPTIONS',
    CREDITS: 'CREDITS',
    SHOP: 'SHOP',
    GAME_OVER: 'GAME_OVER',
    VICTORY: 'VICTORY',
    LEVEL_MAP: 'LEVEL_MAP',
    DIFFICULTY_SELECTION: 'DIFFICULTY_SELECTION',
    BOSS_FIGHT: 'BOSS_FIGHT' 
};